In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5916, 7600, 8661, 3531],
 [5916, 7600, 8661, 979],
 [5916, 8223, 8661, 2396],
 [7407, 1397, 29, 7605, 3619],
 [7407, 1397, 29, 7605, 2747],
 [8451, 5916, 1747, 8661, 3509],
 [4400, 8786, 1732, 7605]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5916 7600 8661 3531]
 [   0    0    0    0 5916 7600 8661  979]
 [   0    0    0    0 5916 8223 8661 2396]
 [   0    0    0 7407 1397   29 7605 3619]
 [   0    0    0 7407 1397   29 7605 2747]
 [   0    0    0 8451 5916 1747 8661 3509]
 [   0    0    0    0 4400 8786 1732 7605]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\AI\movie_review_prediction_simple_RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


array([[[ 0.03252913, -0.02817347,  0.0006292 ,  0.00783078,
          0.02100333,  0.00239649, -0.04610978, -0.02097074,
         -0.00581882,  0.03643696],
        [ 0.03252913, -0.02817347,  0.0006292 ,  0.00783078,
          0.02100333,  0.00239649, -0.04610978, -0.02097074,
         -0.00581882,  0.03643696],
        [ 0.03252913, -0.02817347,  0.0006292 ,  0.00783078,
          0.02100333,  0.00239649, -0.04610978, -0.02097074,
         -0.00581882,  0.03643696],
        [ 0.03252913, -0.02817347,  0.0006292 ,  0.00783078,
          0.02100333,  0.00239649, -0.04610978, -0.02097074,
         -0.00581882,  0.03643696],
        [ 0.04728185,  0.03232043, -0.00480372,  0.04291863,
         -0.01726598,  0.0160724 ,  0.02183429, -0.00650021,
         -0.01507423,  0.03815592],
        [ 0.04673969,  0.04095627, -0.00703341,  0.03727231,
         -0.03428598,  0.00296937,  0.01863389,  0.00601012,
         -0.0171167 , -0.01142943],
        [ 0.0077731 ,  0.02726914,  0.01964191,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5916, 7600, 8661, 3531], dtype=int32)

In [17]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [16]:
import numpy as np
# Reshape to include batch dimension [batch_size, sequence_length]
input_data = np.expand_dims(embedded_docs[0], axis=0)
model.predict(input_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[[ 0.03252913, -0.02817347,  0.0006292 ,  0.00783078,
          0.02100333,  0.00239649, -0.04610978, -0.02097074,
         -0.00581882,  0.03643696],
        [ 0.03252913, -0.02817347,  0.0006292 ,  0.00783078,
          0.02100333,  0.00239649, -0.04610978, -0.02097074,
         -0.00581882,  0.03643696],
        [ 0.03252913, -0.02817347,  0.0006292 ,  0.00783078,
          0.02100333,  0.00239649, -0.04610978, -0.02097074,
         -0.00581882,  0.03643696],
        [ 0.03252913, -0.02817347,  0.0006292 ,  0.00783078,
          0.02100333,  0.00239649, -0.04610978, -0.02097074,
         -0.00581882,  0.03643696],
        [ 0.04728185,  0.03232043, -0.00480372,  0.04291863,
         -0.01726598,  0.0160724 ,  0.02183429, -0.00650021,
         -0.01507423,  0.03815592],
        [ 0.04673969,  0.04095627, -0.00703341,  0.03727231,
         -0.03428598,  0.00296937,  0.01863389,  0.00601012,
         -0.0171167 , -0.01142943],
        [ 0.0077731 ,  0.02726914,  0.01964191,  0.0